Copyright 2026 The Google Research Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

# Vegetation and Soil Parameters Data Processing

In [4]:
import os
from IPython.display import display
import pandas as pd

In [6]:
# Data from Table 8.1 at https://www.ecmwf.int/en/elibrary/81626-ifs-documentation-cy49r1-part-iv-physical-processes
table_8_1_data = {
    "Index": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
    ],
    "Vegetation type": [
        "Crops, mixed farming",
        "Short grass",
        "Evergreen needleleaf trees",
        "Deciduous needleleaf trees",
        "Deciduous broadleaf trees",
        "Evergreen broadleaf trees",
        "Tall grass",
        "Desert",
        "Tundra",
        "Irrigated crops",
        "Semidesert",
        "Ice caps and glaciers",
        "Bogs and marshes",
        "Inland water",
        "Ocean",
        "Evergreen shrubs",
        "Deciduous shrubs",
        "Mixed forest/woodland",
        "Interrupted forest",
        "Water and land mixtures",
    ],
    "H/L veg": [
        "L",
        "L",
        "H",
        "H",
        "H",
        "H",
        "L",
        "-",
        "L",
        "L",
        "L",
        "-",
        "L",
        "-",
        "-",
        "L",
        "L",
        "H",
        "H",
        "L",
    ],
    "rs,min (sm−1)": [
        100,
        100,
        250,
        250,
        175,
        240,
        100,
        250,
        80,
        180,
        150,
        None,
        240,
        None,
        None,
        225,
        225,
        250,
        175,
        150,
    ],
    "cveg": [
        0.90,
        0.85,
        0.90,
        0.90,
        0.90,
        0.99,
        0.70,
        0.0,
        0.50,
        0.90,
        0.10,
        None,
        0.60,
        None,
        None,
        0.50,
        0.50,
        0.90,
        0.90,
        0.60,
    ],
    "gD (hPa−1)": [
        0.0,
        0.0,
        0.03,
        0.03,
        0.03,
        0.03,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        None,
        0.0,
        None,
        None,
        0.0,
        0.0,
        0.03,
        0.03,
        0.0,
    ],
    "ar": [
        5.558,
        10.739,
        6.706,
        7.066,
        5.990,
        7.344,
        8.235,
        4.372,
        8.992,
        5.558,
        4.372,
        None,
        7.344,
        None,
        None,
        6.326,
        6.326,
        4.453,
        4.453,
        None,
    ],
    "br": [
        2.614,
        2.608,
        2.175,
        1.953,
        1.955,
        1.303,
        1.627,
        0.978,
        8.992,
        2.614,
        0.978,
        None,
        1.303,
        None,
        None,
        1.567,
        1.567,
        1.631,
        1.631,
        None,
    ],
}

table_8_1_df = pd.DataFrame(table_8_1_data)
print("DataFrame for Table 8.1:")
table_8_1_df

DataFrame for Table 8.1:

    Index             Vegetation type H/L veg  ...  gD (hPa−1)      ar     br
0       1        Crops, mixed farming       L  ...        0.00   5.558  2.614
1       2                 Short grass       L  ...        0.00  10.739  2.608
2       3  Evergreen needleleaf trees       H  ...        0.03   6.706  2.175
3       4  Deciduous needleleaf trees       H  ...        0.03   7.066  1.953
4       5   Deciduous broadleaf trees       H  ...        0.03   5.990  1.955
5       6   Evergreen broadleaf trees       H  ...        0.03   7.344  1.303
6       7                  Tall grass       L  ...        0.00   8.235  1.627
7       8                      Desert       -  ...        0.00   4.372  0.978
8       9                      Tundra       L  ...        0.00   8.992  8.992
9      10             Irrigated crops       L  ...        0.00   5.558  2.614
10     11                  Semidesert       L  ...        0.00   4.372  0.978
11     12       Ice caps and glaciers       -  ...         NaN     NaN    NaN
12     13            Bogs and marshes       L  ...        0.00   7.344  1.303
13     14                Inland water       -  ...         NaN     NaN    NaN
14     15                       Ocean       -  ...         NaN     NaN    NaN
15     16            Evergreen shrubs       L  ...        0.00   6.326  1.567
16     17            Deciduous shrubs       L  ...        0.00   6.326  1.567
17     18       Mixed forest/woodland       H  ...        0.03   4.453  1.631
18     19          Interrupted forest       H  ...        0.03   4.453  1.631
19     20     Water and land mixtures       L  ...        0.00     NaN    NaN

[20 rows x 8 columns]

In [7]:
table_8_1_df.loc[
    table_8_1_df['Vegetation type'] == 'Water and land mixtures', ['ar', 'br']
] = 0
table_8_1_df

    Index             Vegetation type H/L veg  ...  gD (hPa−1)      ar     br
0       1        Crops, mixed farming       L  ...        0.00   5.558  2.614
1       2                 Short grass       L  ...        0.00  10.739  2.608
2       3  Evergreen needleleaf trees       H  ...        0.03   6.706  2.175
3       4  Deciduous needleleaf trees       H  ...        0.03   7.066  1.953
4       5   Deciduous broadleaf trees       H  ...        0.03   5.990  1.955
5       6   Evergreen broadleaf trees       H  ...        0.03   7.344  1.303
6       7                  Tall grass       L  ...        0.00   8.235  1.627
7       8                      Desert       -  ...        0.00   4.372  0.978
8       9                      Tundra       L  ...        0.00   8.992  8.992
9      10             Irrigated crops       L  ...        0.00   5.558  2.614
10     11                  Semidesert       L  ...        0.00   4.372  0.978
11     12       Ice caps and glaciers       -  ...         NaN     NaN    NaN
12     13            Bogs and marshes       L  ...        0.00   7.344  1.303
13     14                Inland water       -  ...         NaN     NaN    NaN
14     15                       Ocean       -  ...         NaN     NaN    NaN
15     16            Evergreen shrubs       L  ...        0.00   6.326  1.567
16     17            Deciduous shrubs       L  ...        0.00   6.326  1.567
17     18       Mixed forest/woodland       H  ...        0.03   4.453  1.631
18     19          Interrupted forest       H  ...        0.03   4.453  1.631
19     20     Water and land mixtures       L  ...        0.00   0.000  0.000

[20 rows x 8 columns]

In [8]:
table_8_1_df.loc[table_8_1_df['H/L veg'] == 'L', 'H/L veg'] = 1
table_8_1_df.loc[table_8_1_df['H/L veg'] == '-', 'H/L veg'] = 0
table_8_1_df.loc[table_8_1_df['H/L veg'] == 'H', 'H/L veg'] = 2
table_8_1_df

    Index             Vegetation type H/L veg  ...  gD (hPa−1)      ar     br
0       1        Crops, mixed farming       1  ...        0.00   5.558  2.614
1       2                 Short grass       1  ...        0.00  10.739  2.608
2       3  Evergreen needleleaf trees       2  ...        0.03   6.706  2.175
3       4  Deciduous needleleaf trees       2  ...        0.03   7.066  1.953
4       5   Deciduous broadleaf trees       2  ...        0.03   5.990  1.955
5       6   Evergreen broadleaf trees       2  ...        0.03   7.344  1.303
6       7                  Tall grass       1  ...        0.00   8.235  1.627
7       8                      Desert       0  ...        0.00   4.372  0.978
8       9                      Tundra       1  ...        0.00   8.992  8.992
9      10             Irrigated crops       1  ...        0.00   5.558  2.614
10     11                  Semidesert       1  ...        0.00   4.372  0.978
11     12       Ice caps and glaciers       0  ...         NaN     NaN    NaN
12     13            Bogs and marshes       1  ...        0.00   7.344  1.303
13     14                Inland water       0  ...         NaN     NaN    NaN
14     15                       Ocean       0  ...         NaN     NaN    NaN
15     16            Evergreen shrubs       1  ...        0.00   6.326  1.567
16     17            Deciduous shrubs       1  ...        0.00   6.326  1.567
17     18       Mixed forest/woodland       2  ...        0.03   4.453  1.631
18     19          Interrupted forest       2  ...        0.03   4.453  1.631
19     20     Water and land mixtures       1  ...        0.00   0.000  0.000

[20 rows x 8 columns]

For **Ice caps and glaciers (Row 11)**, **Inland water (Row 13)**, **Ocean (Row 14)**, and **Water and land mixtures (Row 19)**, the missing values (NaNs) are due to these surfaces *not being parameterized as active vegetation*.

| Parameter | Recommended Imputation Value | Physical Rationale (IFS Model Context) |
| :--- | :--- | :--- |
| **$H/L \text{ veg}$** (High/Low veg) | **$0$** | Consistent with the existing value for **Ocean** and other non-vegetated types like **Desert**. Represents low or no canopy height. |
| **$r_s, \text{min}$** (Min Stomatal Resistance) | **A very large constant** (e.g., $10^6 \ s \cdot m^{-1}$) | These surfaces have no stomata (no transpiration). This value is used in LSMs to effectively set the **evapotranspiration flux to zero** for the vegetation component of the surface. |
| **$c_{veg}$** (Vegetation Coverage) | **$0.00$** | No vegetation fraction, as seen in the existing value for **Ocean** and **Desert** is $0.00$. This is the clearest and safest imputation. |
| **$g_D$** (Decoupling Factor) | **$0.00$** | Related to vegetation's control over water flux; set to zero for non-vegetated surfaces where the formula is irrelevant. |
| **$a_r$ and $b_r$** (Root Distribution Attenuation) | **$0.000$ for both** | These coefficients define the **exponential root profile** ($f(z) \propto e^{-a_r z} / b_r$). For non-vegetated surfaces, there are **no roots**, so the entire root distribution function must be zero, achieved by setting these coefficients to $0$. This aligns with the existing $0.000$ values for **Water and land mixtures** (Row 19).  |

---

In [9]:
new_row_rs_min = (
    table_8_1_df['rs,min (sm−1)'].max() * 2
)  # Using 2 max instead of 10^6 to avoid large numbers for ML training.
new_row_data = {
    'Index': [0],
    'Vegetation type': [
        'Non-vegetated'
    ],  # Include everything (Ice caps and glaciers, Inland water, and Ocean)
    'H/L veg': [0],
    'rs,min (sm−1)': [new_row_rs_min],
    'cveg': [0],
    'gD (hPa−1)': [0],
    'ar': [0],
    'br': [0],
}
new_row_df = pd.DataFrame(new_row_data)
table_8_1_df = pd.concat([new_row_df, table_8_1_df], ignore_index=True)
print("DataFrame for Table 8.1 with 'Non-vegetated' row added:")
table_8_1_df

DataFrame for Table 8.1 with 'Non-vegetated' row added:

    Index             Vegetation type H/L veg  ...  gD (hPa−1)      ar     br
0       0               Non-vegetated       0  ...        0.00   0.000  0.000
1       1        Crops, mixed farming       1  ...        0.00   5.558  2.614
2       2                 Short grass       1  ...        0.00  10.739  2.608
3       3  Evergreen needleleaf trees       2  ...        0.03   6.706  2.175
4       4  Deciduous needleleaf trees       2  ...        0.03   7.066  1.953
5       5   Deciduous broadleaf trees       2  ...        0.03   5.990  1.955
6       6   Evergreen broadleaf trees       2  ...        0.03   7.344  1.303
7       7                  Tall grass       1  ...        0.00   8.235  1.627
8       8                      Desert       0  ...        0.00   4.372  0.978
9       9                      Tundra       1  ...        0.00   8.992  8.992
10     10             Irrigated crops       1  ...        0.00   5.558  2.614
11     11                  Semidesert       1  ...        0.00   4.372  0.978
12     12       Ice caps and glaciers       0  ...         NaN     NaN    NaN
13     13            Bogs and marshes       1  ...        0.00   7.344  1.303
14     14                Inland water       0  ...         NaN     NaN    NaN
15     15                       Ocean       0  ...         NaN     NaN    NaN
16     16            Evergreen shrubs       1  ...        0.00   6.326  1.567
17     17            Deciduous shrubs       1  ...        0.00   6.326  1.567
18     18       Mixed forest/woodland       2  ...        0.03   4.453  1.631
19     19          Interrupted forest       2  ...        0.03   4.453  1.631
20     20     Water and land mixtures       1  ...        0.00   0.000  0.000

[21 rows x 8 columns]

In [10]:
veg_params = table_8_1_df.drop(
    columns=['Index', 'H/L veg', 'Vegetation type', 'gD (hPa−1)']
)
display(veg_params)

    rs,min (sm−1)  cveg      ar     br
0           500.0  0.00   0.000  0.000
1           100.0  0.90   5.558  2.614
2           100.0  0.85  10.739  2.608
3           250.0  0.90   6.706  2.175
4           250.0  0.90   7.066  1.953
5           175.0  0.90   5.990  1.955
6           240.0  0.99   7.344  1.303
7           100.0  0.70   8.235  1.627
8           250.0  0.00   4.372  0.978
9            80.0  0.50   8.992  8.992
10          180.0  0.90   5.558  2.614
11          150.0  0.10   4.372  0.978
12            NaN   NaN     NaN    NaN
13          240.0  0.60   7.344  1.303
14            NaN   NaN     NaN    NaN
15            NaN   NaN     NaN    NaN
16          225.0  0.50   6.326  1.567
17          225.0  0.50   6.326  1.567
18          250.0  0.90   4.453  1.631
19          175.0  0.90   4.453  1.631
20          150.0  0.60   0.000  0.000

In [11]:
print('Before normalizing')
display(veg_params)
veg_params_normalized = veg_params / veg_params.iloc[1:].max(0)
veg_params_normalized['cveg'] = veg_params['cveg']
print('\nAfter normalizing')
display(veg_params_normalized)

Before normalizing

    rs,min (sm−1)  cveg      ar     br
0           500.0  0.00   0.000  0.000
1           100.0  0.90   5.558  2.614
2           100.0  0.85  10.739  2.608
3           250.0  0.90   6.706  2.175
4           250.0  0.90   7.066  1.953
5           175.0  0.90   5.990  1.955
6           240.0  0.99   7.344  1.303
7           100.0  0.70   8.235  1.627
8           250.0  0.00   4.372  0.978
9            80.0  0.50   8.992  8.992
10          180.0  0.90   5.558  2.614
11          150.0  0.10   4.372  0.978
12            NaN   NaN     NaN    NaN
13          240.0  0.60   7.344  1.303
14            NaN   NaN     NaN    NaN
15            NaN   NaN     NaN    NaN
16          225.0  0.50   6.326  1.567
17          225.0  0.50   6.326  1.567
18          250.0  0.90   4.453  1.631
19          175.0  0.90   4.453  1.631
20          150.0  0.60   0.000  0.000

After normalizing

    rs,min (sm−1)  cveg        ar        br
0            2.00  0.00  0.000000  0.000000
1            0.40  0.90  0.517553  0.290703
2            0.40  0.85  1.000000  0.290036
3            1.00  0.90  0.624453  0.241882
4            1.00  0.90  0.657976  0.217193
5            0.70  0.90  0.557780  0.217415
6            0.96  0.99  0.683863  0.144907
7            0.40  0.70  0.766831  0.180939
8            1.00  0.00  0.407114  0.108763
9            0.32  0.50  0.837322  1.000000
10           0.72  0.90  0.517553  0.290703
11           0.60  0.10  0.407114  0.108763
12            NaN   NaN       NaN       NaN
13           0.96  0.60  0.683863  0.144907
14            NaN   NaN       NaN       NaN
15            NaN   NaN       NaN       NaN
16           0.90  0.50  0.589068  0.174266
17           0.90  0.50  0.589068  0.174266
18           1.00  0.90  0.414657  0.181383
19           0.70  0.90  0.414657  0.181383
20           0.60  0.60  0.000000  0.000000

In [12]:
# Soil data from Table 8.8 at https://www.ecmwf.int/en/elibrary/81626-ifs-documentation-cy49r1-part-iv-physical-processes

table_8_8_data = {
    'Texture': [
        'Coarse',
        'Medium',
        'Medium-Fine',
        'Fine',
        'Very Fine',
        'Ext.Trop. Organic',
        'Trop. Organic',
        'Old-Loamy (CH)',
    ],
    'θsat': [0.403, 0.439, 0.430, 0.520, 0.614, 0.766, 0.439, 0.472],
    'θcap': [0.244, 0.347, 0.383, 0.448, 0.541, 0.663, 0.347, 0.323],
    'θpwp': [0.059, 0.151, 0.133, 0.279, 0.335, 0.267, 0.151, 0.171],
    'θres': [0.025, 0.010, 0.010, 0.010, 0.010, 0.010, 0.010, None],
    'θcap − θpwp': [0.185, 0.196, 0.251, 0.170, 0.207, 0.396, 0.196, 0.151],
}

table_8_8_df = pd.DataFrame(table_8_8_data)
display(table_8_8_df)

             Texture   θsat   θcap   θpwp   θres  θcap − θpwp
0             Coarse  0.403  0.244  0.059  0.025        0.185
1             Medium  0.439  0.347  0.151  0.010        0.196
2        Medium-Fine  0.430  0.383  0.133  0.010        0.251
3               Fine  0.520  0.448  0.279  0.010        0.170
4          Very Fine  0.614  0.541  0.335  0.010        0.207
5  Ext.Trop. Organic  0.766  0.663  0.267  0.010        0.396
6      Trop. Organic  0.439  0.347  0.151  0.010        0.196
7     Old-Loamy (CH)  0.472  0.323  0.171    NaN        0.151

### Imputation for Open Water/Deep Water


| Parameter | Recommended Imputation Value | Physical Rationale |
| :--- | :--- | :--- |
| **$\theta_{\text{sat}}$ (Saturated Water Content)** | **$1.000$** | This is the volume fraction of water when saturated. In pure water, the volume of water equals the total volume of the medium. Some models use a value slightly less than 1 (e.g., $0.999$) to avoid division by zero errors in soil porosity calculations, but $1.000$ represents the physics best. |
| **$\theta_{\text{cap}}$ (Field Capacity)** | **$1.000$** | Field capacity is the water content after gravitational drainage. For open water, there is no matrix potential that would cause water to drain from the bulk liquid (unless it's draining out of the grid box, which is handled by a runoff or river flow scheme, not this parameter). Thus, the "holding capacity" is the same as the saturation point. |
| **$\theta_{\text{pwp}}$ (Permanent Wilting Point)** | **$0.000$** | This is the most crucial parameter. Wilting Point defines the minimum water content *available* for transfer. Setting this to zero means **all** the water in the layer ($\theta_{\text{sat}} - \theta_{\text{res}}$) is considered **plant-available water** (PAW). This is consistent with water being readily available for evaporation/sublimation. |
| **$\theta_{\text{res}}$ (Residual Water Content)** | **$0.000$** | This represents water held so tightly by the soil matrix that it can't be removed, even by plants. Since open water has no solid matrix, the residual water should be zero. |
| **$\theta_{\text{cap}} - \theta_{\text{pwp}}$ (Plant Available Water)** | **$1.000$** | This column is derived as $\theta_{\text{cap}} - \theta_{\text{pwp}}$, and using the imputed values yields $1.000 - 0.000 = 1.000$. This confirms that all the water in the layer is available for flux. |



### Imputation for $\theta_{\text{res}}$ for Old-Loamy (CH)

| Texture | $\theta_{\text{res}}$ | Notes |
| :--- | :--- | :--- |
| Old-Loamy (CH) | $\mathbf{0.010}$ | Using the median/mode of the existing values for stability and consistency with the other loamy/fine textures. |

In [13]:
# Add the 'Water' row
water_row_data = {
    'Texture': ['Water'],
    'θsat': [1.0],
    'θcap': [1.0],
    'θpwp': [0.0],
    'θres': [0.0],
    'θcap − θpwp': [1.0],
}
water_row_df = pd.DataFrame(water_row_data)
table_8_8_df = pd.concat([water_row_df, table_8_8_df], ignore_index=True)
table_8_8_df.loc[table_8_8_df['Texture'] == 'Old-Loamy (CH)', 'θres'] = 0.01

print("DataFrame for Table 8.8 with 'Water' row:")
display(table_8_8_df)

DataFrame for Table 8.8 with 'Water' row:

             Texture   θsat   θcap   θpwp   θres  θcap − θpwp
0              Water  1.000  1.000  0.000  0.000        1.000
1             Coarse  0.403  0.244  0.059  0.025        0.185
2             Medium  0.439  0.347  0.151  0.010        0.196
3        Medium-Fine  0.430  0.383  0.133  0.010        0.251
4               Fine  0.520  0.448  0.279  0.010        0.170
5          Very Fine  0.614  0.541  0.335  0.010        0.207
6  Ext.Trop. Organic  0.766  0.663  0.267  0.010        0.396
7      Trop. Organic  0.439  0.347  0.151  0.010        0.196
8     Old-Loamy (CH)  0.472  0.323  0.171  0.010        0.151

In [14]:
soil_params = table_8_8_df.drop(columns=['Texture', 'θres', 'θcap − θpwp'])
display(soil_params)

    θsat   θcap   θpwp
0  1.000  1.000  0.000
1  0.403  0.244  0.059
2  0.439  0.347  0.151
3  0.430  0.383  0.133
4  0.520  0.448  0.279
5  0.614  0.541  0.335
6  0.766  0.663  0.267
7  0.439  0.347  0.151
8  0.472  0.323  0.171

In [15]:
print('Before normalizing')
display(soil_params)
soil_params_normalized = soil_params / soil_params.max(0)
print('\nAfter normalizing')
display(soil_params_normalized)

Before normalizing

    θsat   θcap   θpwp
0  1.000  1.000  0.000
1  0.403  0.244  0.059
2  0.439  0.347  0.151
3  0.430  0.383  0.133
4  0.520  0.448  0.279
5  0.614  0.541  0.335
6  0.766  0.663  0.267
7  0.439  0.347  0.151
8  0.472  0.323  0.171

After normalizing

    θsat   θcap      θpwp
0  1.000  1.000  0.000000
1  0.403  0.244  0.176119
2  0.439  0.347  0.450746
3  0.430  0.383  0.397015
4  0.520  0.448  0.832836
5  0.614  0.541  1.000000
6  0.766  0.663  0.797015
7  0.439  0.347  0.450746
8  0.472  0.323  0.510448

### Ground heat flux has its own soil parameters, different from table_8_8_df. It is defined below

In [16]:
data = {
    'Texture Class': [
        'Coarse (Sand)',
        'Medium (Loam)',
        'Medium-Fine',
        'Fine (Clay)',
        'Very Fine (Clay)',
        'Organic',
        'Trop. Organic',
    ],
    # K_dry [W m⁻¹K⁻¹]
    'K_dry [W m⁻¹K⁻¹]': [0.29, 0.24, 0.20, 0.16, 0.12, 0.05, 0.24],
    # K_sat [W m⁻¹K⁻¹]
    'K_sat [W m⁻¹K⁻¹]': [2.50, 2.05, 1.83, 1.58, 1.33, 0.50, 2.00],
    # C_dry [10⁶ J m⁻³K⁻¹]
    'C_dry [10⁶ J m⁻³K⁻¹]': [1.28, 1.38, 1.48, 1.58, 1.68, 0.51, 1.38],
    # θ_sat [m³/m³] (using the Theta character 'θ')
    'θ_sat [m³/m³]': [0.395, 0.435, 0.485, 0.482, 0.482, 0.835, 0.439],
}

ground_heat_soil_params = pd.DataFrame(data)

display(ground_heat_soil_params)

      Texture Class  K_dry [W m⁻¹K⁻¹]  ...  C_dry [10⁶ J m⁻³K⁻¹]  θ_sat [m³/m³]
0     Coarse (Sand)              0.29  ...                  1.28          0.395
1     Medium (Loam)              0.24  ...                  1.38          0.435
2       Medium-Fine              0.20  ...                  1.48          0.485
3       Fine (Clay)              0.16  ...                  1.58          0.482
4  Very Fine (Clay)              0.12  ...                  1.68          0.482
5           Organic              0.05  ...                  0.51          0.835
6     Trop. Organic              0.24  ...                  1.38          0.439

[7 rows x 5 columns]



### Values to Define Water's Properties



| Parameter | Imputation Value for Open Water | Physical Basis |
| :--- | :--- | :--- |
| **$\text{K}_{\text{dry}}$** [$\text{W m}^{-1} \text{K}^{-1}$] | **$\mathbf{0.0}$** | Water has no "dry" state (no solid matrix). |
| **$\text{K}_{\text{sat}}$** [$\text{W m}^{-1} \text{K}^{-1}$] | **$\approx \mathbf{0.60}$** | This is the thermal conductivity of liquid water (e.g., $0.60 \text{ W/m} \cdot \text{K}$ at $20^\circ \text{C}$). |
| **$\text{C}_{\text{dry}}$** [$10^6 \text{ J m}^{-3} \text{K}^{-1}$] | **$\approx \mathbf{4.18}$** | This is the volumetric heat capacity of water (which is its specific heat capacity $\times$ density). |
| **$\theta_{\text{sat}}$** [$\text{m}^3/\text{m}^3$] | **$\mathbf{1.00}$** | Open water is 100% water by volume. |

In [17]:
new_C_dry_value = (
    ground_heat_soil_params['C_dry [10⁶ J m⁻³K⁻¹]'].max() * 2
)  # Instead of actual value, just to avoid big numbers for ML training.
water_gh_row_data = {
    'Texture Class': ['Water'],
    'K_dry [W m⁻¹K⁻¹]': [0.0],
    'K_sat [W m⁻¹K⁻¹]': [0.6],
    'C_dry [10⁶ J m⁻³K⁻¹]': [new_C_dry_value],
    'θ_sat [m³/m³]': [1.0],
}
water_gh_row_df = pd.DataFrame(water_gh_row_data)
ground_heat_soil_params = pd.concat(
    [water_gh_row_df, ground_heat_soil_params], ignore_index=True
)
print("DataFrame for Ground Heat Soil Parameters with 'Water' row:")
display(ground_heat_soil_params)

DataFrame for Ground Heat Soil Parameters with 'Water' row:

      Texture Class  K_dry [W m⁻¹K⁻¹]  ...  C_dry [10⁶ J m⁻³K⁻¹]  θ_sat [m³/m³]
0             Water              0.00  ...                  3.36          1.000
1     Coarse (Sand)              0.29  ...                  1.28          0.395
2     Medium (Loam)              0.24  ...                  1.38          0.435
3       Medium-Fine              0.20  ...                  1.48          0.485
4       Fine (Clay)              0.16  ...                  1.58          0.482
5  Very Fine (Clay)              0.12  ...                  1.68          0.482
6           Organic              0.05  ...                  0.51          0.835
7     Trop. Organic              0.24  ...                  1.38          0.439

[8 rows x 5 columns]

In [18]:
ground_heat_soil_params = ground_heat_soil_params.drop(
    columns=['Texture Class']
)
display(ground_heat_soil_params)

   K_dry [W m⁻¹K⁻¹]  K_sat [W m⁻¹K⁻¹]  C_dry [10⁶ J m⁻³K⁻¹]  θ_sat [m³/m³]
0              0.00              0.60                  3.36          1.000
1              0.29              2.50                  1.28          0.395
2              0.24              2.05                  1.38          0.435
3              0.20              1.83                  1.48          0.485
4              0.16              1.58                  1.58          0.482
5              0.12              1.33                  1.68          0.482
6              0.05              0.50                  0.51          0.835
7              0.24              2.00                  1.38          0.439

In [19]:
print('Before normalizing')
display(ground_heat_soil_params)
ground_heat_soil_params_normalized = (
    ground_heat_soil_params / ground_heat_soil_params.iloc[1:].max(0)
)
print('\nAfter normalizing')
display(ground_heat_soil_params_normalized)

Before normalizing

   K_dry [W m⁻¹K⁻¹]  K_sat [W m⁻¹K⁻¹]  C_dry [10⁶ J m⁻³K⁻¹]  θ_sat [m³/m³]
0              0.00              0.60                  3.36          1.000
1              0.29              2.50                  1.28          0.395
2              0.24              2.05                  1.38          0.435
3              0.20              1.83                  1.48          0.485
4              0.16              1.58                  1.58          0.482
5              0.12              1.33                  1.68          0.482
6              0.05              0.50                  0.51          0.835
7              0.24              2.00                  1.38          0.439

After normalizing

   K_dry [W m⁻¹K⁻¹]  K_sat [W m⁻¹K⁻¹]  C_dry [10⁶ J m⁻³K⁻¹]  θ_sat [m³/m³]
0          0.000000             0.240              2.000000       1.197605
1          1.000000             1.000              0.761905       0.473054
2          0.827586             0.820              0.821429       0.520958
3          0.689655             0.732              0.880952       0.580838
4          0.551724             0.632              0.940476       0.577246
5          0.413793             0.532              1.000000       0.577246
6          0.172414             0.200              0.303571       1.000000
7          0.827586             0.800              0.821429       0.525749

In [20]:
# Define the directory path
save_dir = '../data/'
os.makedirs(save_dir, exist_ok=True)

# 1. Save Vegetation Parameters
veg_csv_path = f'{save_dir}/veg_params.csv'
veg_params_normalized.to_csv(veg_csv_path, index=False)
print(f'Saved: {veg_csv_path}')

# 2. Save Soil Parameters
soil_csv_path = f'{save_dir}/soil_params.csv'
soil_params_normalized.to_csv(soil_csv_path, index=False)
print(f'Saved: {soil_csv_path}')

# 3. Save Ground Heat Soil Parameters
gh_csv_path = f'{save_dir}/ground_heat_params.csv'
ground_heat_soil_params_normalized.to_csv(gh_csv_path, index=False)
print(f'Saved: {gh_csv_path}')